version: '3.1'

networks:
  k6:
  grafana:

services:
  influxdb:
    image: influxdb:latest
#    entrypoint: /bin/sh
#    user: root
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    volumes:
      - influxdb-volume:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
#    entrypoint: /bin/sh
#    user: root
    networks:
      - grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-volume:/var/lib/grafana

  k6:
    image: loadimpact/k6:latest
#    entrypoint: /bin/sh
#    user: root
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://172.19.0.1:8086/k6
