default: &defaults
  parallelism: 1
  working_directory: ~/Perf-Test-DIL

install_docker_client: &install_docker_client
    run:
      name: Install Docker client
      command: |
        set -x
        VER="20.10.6"
        curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/staticstable/x86_64/docker-$VER.tgz
        tar zxvf /tmp/docker-$VER.tgz -C /tmp
        mv /tmp/docker/* /usr/bin
install_docker_compose: &install_docker_compose
    run:
      name: Install Docker Compose
      command: |
        set -x
        curl -L https://github.com/docker/compose/releases/download/1.29.1/docker-compose-Linux-x86_64 > /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
start_container_run_load: &start_container_run_load
    run:
      name: Start container and Run Load Testing
      command: |
        set -x
        docker-compose up -d
        docker-compose run -v $HOME/performance-test.js:/scripts k6 run /scripts/performance-test.js
version: 2
jobs:
  run_performance_tests:
    <<: *defaults
    # Use `machine` executor because the Docker executor cannot mount volumes
    machine: true
    steps:
      - checkout
      - install_docker_client
      - install_docker_compose
      - start_container_run_load
workflows:
  version: 2
  build-and-test:
    jobs:
      - run_performance_tests
