version: 2.1
workflows:
  Docker Compose:
    jobs:
      working_directory: ~/Perf-Test-DIL
      steps:
        - checkout
        - run:
            name: Install Docker client
            command: |
              set -x
              VER="20.10.6"
              curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
              tar -xz -C /tmp -f /tmp/docker-$VER.tgz
              mv /tmp/docker/* /usr/bin
        - run:
            name: Install Docker Compose
            command: |
              set -x
              curl -L https://github.com/docker/compose/releases/download/1.29.1/docker-compose-Linux-x86_64 > /usr/local/bin/docker-compose
              chmod +x /usr/local/bin/docker-compose
        - run:
            name: Start container and Run Load Testing
            command: |
              set -x
              docker-compose up -d
              # docker-compose will start 2 containers, the one with service will be named `contacts`
              # we start another container with curl in the same network as `contacts`, this way we have
              # all exposed ports from `contacts` available on `localhost` in this new container
              docker-compose run -v $PWD/performance-test.js:/scripts k6 run /scripts/performance-test.js
